# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/NVIDIA-OptiX-SDK-6.0.0-linux64/SDK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jason/CUDA/Optix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/CUDA/Optix/CMakeFiles /home/jason/CUDA/Optix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/CUDA/Optix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named optixBuffersOfBuffers

# Build rule for target.
optixBuffersOfBuffers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixBuffersOfBuffers
.PHONY : optixBuffersOfBuffers

# fast build rule for target.
optixBuffersOfBuffers/fast:
	$(MAKE) -f optixBuffersOfBuffers/CMakeFiles/optixBuffersOfBuffers.dir/build.make optixBuffersOfBuffers/CMakeFiles/optixBuffersOfBuffers.dir/build
.PHONY : optixBuffersOfBuffers/fast

#=============================================================================
# Target rules for targets named optixCallablePrograms

# Build rule for target.
optixCallablePrograms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixCallablePrograms
.PHONY : optixCallablePrograms

# fast build rule for target.
optixCallablePrograms/fast:
	$(MAKE) -f optixCallablePrograms/CMakeFiles/optixCallablePrograms.dir/build.make optixCallablePrograms/CMakeFiles/optixCallablePrograms.dir/build
.PHONY : optixCallablePrograms/fast

#=============================================================================
# Target rules for targets named optixCompressedTexture

# Build rule for target.
optixCompressedTexture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixCompressedTexture
.PHONY : optixCompressedTexture

# fast build rule for target.
optixCompressedTexture/fast:
	$(MAKE) -f optixCompressedTexture/CMakeFiles/optixCompressedTexture.dir/build.make optixCompressedTexture/CMakeFiles/optixCompressedTexture.dir/build
.PHONY : optixCompressedTexture/fast

#=============================================================================
# Target rules for targets named optixConsole

# Build rule for target.
optixConsole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixConsole
.PHONY : optixConsole

# fast build rule for target.
optixConsole/fast:
	$(MAKE) -f optixConsole/CMakeFiles/optixConsole.dir/build.make optixConsole/CMakeFiles/optixConsole.dir/build
.PHONY : optixConsole/fast

#=============================================================================
# Target rules for targets named optixDenoiser

# Build rule for target.
optixDenoiser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixDenoiser
.PHONY : optixDenoiser

# fast build rule for target.
optixDenoiser/fast:
	$(MAKE) -f optixDenoiser/CMakeFiles/optixDenoiser.dir/build.make optixDenoiser/CMakeFiles/optixDenoiser.dir/build
.PHONY : optixDenoiser/fast

#=============================================================================
# Target rules for targets named optixDeviceQuery

# Build rule for target.
optixDeviceQuery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixDeviceQuery
.PHONY : optixDeviceQuery

# fast build rule for target.
optixDeviceQuery/fast:
	$(MAKE) -f optixDeviceQuery/CMakeFiles/optixDeviceQuery.dir/build.make optixDeviceQuery/CMakeFiles/optixDeviceQuery.dir/build
.PHONY : optixDeviceQuery/fast

#=============================================================================
# Target rules for targets named optixDynamicGeometry

# Build rule for target.
optixDynamicGeometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixDynamicGeometry
.PHONY : optixDynamicGeometry

# fast build rule for target.
optixDynamicGeometry/fast:
	$(MAKE) -f optixDynamicGeometry/CMakeFiles/optixDynamicGeometry.dir/build.make optixDynamicGeometry/CMakeFiles/optixDynamicGeometry.dir/build
.PHONY : optixDynamicGeometry/fast

#=============================================================================
# Target rules for targets named optixGeometryTriangles

# Build rule for target.
optixGeometryTriangles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixGeometryTriangles
.PHONY : optixGeometryTriangles

# fast build rule for target.
optixGeometryTriangles/fast:
	$(MAKE) -f optixGeometryTriangles/CMakeFiles/optixGeometryTriangles.dir/build.make optixGeometryTriangles/CMakeFiles/optixGeometryTriangles.dir/build
.PHONY : optixGeometryTriangles/fast

#=============================================================================
# Target rules for targets named optixHello

# Build rule for target.
optixHello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixHello
.PHONY : optixHello

# fast build rule for target.
optixHello/fast:
	$(MAKE) -f optixHello/CMakeFiles/optixHello.dir/build.make optixHello/CMakeFiles/optixHello.dir/build
.PHONY : optixHello/fast

#=============================================================================
# Target rules for targets named optixInstancing

# Build rule for target.
optixInstancing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixInstancing
.PHONY : optixInstancing

# fast build rule for target.
optixInstancing/fast:
	$(MAKE) -f optixInstancing/CMakeFiles/optixInstancing.dir/build.make optixInstancing/CMakeFiles/optixInstancing.dir/build
.PHONY : optixInstancing/fast

#=============================================================================
# Target rules for targets named optixMDLDisplacement

# Build rule for target.
optixMDLDisplacement: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixMDLDisplacement
.PHONY : optixMDLDisplacement

# fast build rule for target.
optixMDLDisplacement/fast:
	$(MAKE) -f optixMDLDisplacement/CMakeFiles/optixMDLDisplacement.dir/build.make optixMDLDisplacement/CMakeFiles/optixMDLDisplacement.dir/build
.PHONY : optixMDLDisplacement/fast

#=============================================================================
# Target rules for targets named optixMDLExpressions

# Build rule for target.
optixMDLExpressions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixMDLExpressions
.PHONY : optixMDLExpressions

# fast build rule for target.
optixMDLExpressions/fast:
	$(MAKE) -f optixMDLExpressions/CMakeFiles/optixMDLExpressions.dir/build.make optixMDLExpressions/CMakeFiles/optixMDLExpressions.dir/build
.PHONY : optixMDLExpressions/fast

#=============================================================================
# Target rules for targets named optixMDLSphere

# Build rule for target.
optixMDLSphere: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixMDLSphere
.PHONY : optixMDLSphere

# fast build rule for target.
optixMDLSphere/fast:
	$(MAKE) -f optixMDLSphere/CMakeFiles/optixMDLSphere.dir/build.make optixMDLSphere/CMakeFiles/optixMDLSphere.dir/build
.PHONY : optixMDLSphere/fast

#=============================================================================
# Target rules for targets named optixMeshViewer

# Build rule for target.
optixMeshViewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixMeshViewer
.PHONY : optixMeshViewer

# fast build rule for target.
optixMeshViewer/fast:
	$(MAKE) -f optixMeshViewer/CMakeFiles/optixMeshViewer.dir/build.make optixMeshViewer/CMakeFiles/optixMeshViewer.dir/build
.PHONY : optixMeshViewer/fast

#=============================================================================
# Target rules for targets named optixMotionBlur

# Build rule for target.
optixMotionBlur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixMotionBlur
.PHONY : optixMotionBlur

# fast build rule for target.
optixMotionBlur/fast:
	$(MAKE) -f optixMotionBlur/CMakeFiles/optixMotionBlur.dir/build.make optixMotionBlur/CMakeFiles/optixMotionBlur.dir/build
.PHONY : optixMotionBlur/fast

#=============================================================================
# Target rules for targets named optixParticles

# Build rule for target.
optixParticles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixParticles
.PHONY : optixParticles

# fast build rule for target.
optixParticles/fast:
	$(MAKE) -f optixParticles/CMakeFiles/optixParticles.dir/build.make optixParticles/CMakeFiles/optixParticles.dir/build
.PHONY : optixParticles/fast

#=============================================================================
# Target rules for targets named optixPathTracer

# Build rule for target.
optixPathTracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixPathTracer
.PHONY : optixPathTracer

# fast build rule for target.
optixPathTracer/fast:
	$(MAKE) -f optixPathTracer/CMakeFiles/optixPathTracer.dir/build.make optixPathTracer/CMakeFiles/optixPathTracer.dir/build
.PHONY : optixPathTracer/fast

#=============================================================================
# Target rules for targets named optixPrimitiveIndexOffsets

# Build rule for target.
optixPrimitiveIndexOffsets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixPrimitiveIndexOffsets
.PHONY : optixPrimitiveIndexOffsets

# fast build rule for target.
optixPrimitiveIndexOffsets/fast:
	$(MAKE) -f optixPrimitiveIndexOffsets/CMakeFiles/optixPrimitiveIndexOffsets.dir/build.make optixPrimitiveIndexOffsets/CMakeFiles/optixPrimitiveIndexOffsets.dir/build
.PHONY : optixPrimitiveIndexOffsets/fast

#=============================================================================
# Target rules for targets named optixRaycasting

# Build rule for target.
optixRaycasting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixRaycasting
.PHONY : optixRaycasting

# fast build rule for target.
optixRaycasting/fast:
	$(MAKE) -f optixRaycasting/CMakeFiles/optixRaycasting.dir/build.make optixRaycasting/CMakeFiles/optixRaycasting.dir/build
.PHONY : optixRaycasting/fast

#=============================================================================
# Target rules for targets named optixSelector

# Build rule for target.
optixSelector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixSelector
.PHONY : optixSelector

# fast build rule for target.
optixSelector/fast:
	$(MAKE) -f optixSelector/CMakeFiles/optixSelector.dir/build.make optixSelector/CMakeFiles/optixSelector.dir/build
.PHONY : optixSelector/fast

#=============================================================================
# Target rules for targets named optixSphere

# Build rule for target.
optixSphere: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixSphere
.PHONY : optixSphere

# fast build rule for target.
optixSphere/fast:
	$(MAKE) -f optixSphere/CMakeFiles/optixSphere.dir/build.make optixSphere/CMakeFiles/optixSphere.dir/build
.PHONY : optixSphere/fast

#=============================================================================
# Target rules for targets named optixSpherePP

# Build rule for target.
optixSpherePP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixSpherePP
.PHONY : optixSpherePP

# fast build rule for target.
optixSpherePP/fast:
	$(MAKE) -f optixSpherePP/CMakeFiles/optixSpherePP.dir/build.make optixSpherePP/CMakeFiles/optixSpherePP.dir/build
.PHONY : optixSpherePP/fast

#=============================================================================
# Target rules for targets named optixSSIMPredictor

# Build rule for target.
optixSSIMPredictor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixSSIMPredictor
.PHONY : optixSSIMPredictor

# fast build rule for target.
optixSSIMPredictor/fast:
	$(MAKE) -f optixSSIMPredictor/CMakeFiles/optixSSIMPredictor.dir/build.make optixSSIMPredictor/CMakeFiles/optixSSIMPredictor.dir/build
.PHONY : optixSSIMPredictor/fast

#=============================================================================
# Target rules for targets named optixTextureSampler

# Build rule for target.
optixTextureSampler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixTextureSampler
.PHONY : optixTextureSampler

# fast build rule for target.
optixTextureSampler/fast:
	$(MAKE) -f optixTextureSampler/CMakeFiles/optixTextureSampler.dir/build.make optixTextureSampler/CMakeFiles/optixTextureSampler.dir/build
.PHONY : optixTextureSampler/fast

#=============================================================================
# Target rules for targets named optixTutorial

# Build rule for target.
optixTutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixTutorial
.PHONY : optixTutorial

# fast build rule for target.
optixTutorial/fast:
	$(MAKE) -f optixTutorial/CMakeFiles/optixTutorial.dir/build.make optixTutorial/CMakeFiles/optixTutorial.dir/build
.PHONY : optixTutorial/fast

#=============================================================================
# Target rules for targets named optixWhitted

# Build rule for target.
optixWhitted: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 optixWhitted
.PHONY : optixWhitted

# fast build rule for target.
optixWhitted/fast:
	$(MAKE) -f optixWhitted/CMakeFiles/optixWhitted.dir/build.make optixWhitted/CMakeFiles/optixWhitted.dir/build
.PHONY : optixWhitted/fast

#=============================================================================
# Target rules for targets named primeInstancing

# Build rule for target.
primeInstancing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeInstancing
.PHONY : primeInstancing

# fast build rule for target.
primeInstancing/fast:
	$(MAKE) -f primeInstancing/CMakeFiles/primeInstancing.dir/build.make primeInstancing/CMakeFiles/primeInstancing.dir/build
.PHONY : primeInstancing/fast

#=============================================================================
# Target rules for targets named primeMasking

# Build rule for target.
primeMasking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeMasking
.PHONY : primeMasking

# fast build rule for target.
primeMasking/fast:
	$(MAKE) -f primeMasking/CMakeFiles/primeMasking.dir/build.make primeMasking/CMakeFiles/primeMasking.dir/build
.PHONY : primeMasking/fast

#=============================================================================
# Target rules for targets named primeMultiBuffering

# Build rule for target.
primeMultiBuffering: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeMultiBuffering
.PHONY : primeMultiBuffering

# fast build rule for target.
primeMultiBuffering/fast:
	$(MAKE) -f primeMultiBuffering/CMakeFiles/primeMultiBuffering.dir/build.make primeMultiBuffering/CMakeFiles/primeMultiBuffering.dir/build
.PHONY : primeMultiBuffering/fast

#=============================================================================
# Target rules for targets named primeMultiGpu

# Build rule for target.
primeMultiGpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeMultiGpu
.PHONY : primeMultiGpu

# fast build rule for target.
primeMultiGpu/fast:
	$(MAKE) -f primeMultiGpu/CMakeFiles/primeMultiGpu.dir/build.make primeMultiGpu/CMakeFiles/primeMultiGpu.dir/build
.PHONY : primeMultiGpu/fast

#=============================================================================
# Target rules for targets named primeSimple

# Build rule for target.
primeSimple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeSimple
.PHONY : primeSimple

# fast build rule for target.
primeSimple/fast:
	$(MAKE) -f primeSimple/CMakeFiles/primeSimple.dir/build.make primeSimple/CMakeFiles/primeSimple.dir/build
.PHONY : primeSimple/fast

#=============================================================================
# Target rules for targets named primeSimplePP

# Build rule for target.
primeSimplePP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primeSimplePP
.PHONY : primeSimplePP

# fast build rule for target.
primeSimplePP/fast:
	$(MAKE) -f primeSimplePP/CMakeFiles/primeSimplePP.dir/build.make primeSimplePP/CMakeFiles/primeSimplePP.dir/build
.PHONY : primeSimplePP/fast

#=============================================================================
# Target rules for targets named sutil_sdk

# Build rule for target.
sutil_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sutil_sdk
.PHONY : sutil_sdk

# fast build rule for target.
sutil_sdk/fast:
	$(MAKE) -f sutil/CMakeFiles/sutil_sdk.dir/build.make sutil/CMakeFiles/sutil_sdk.dir/build
.PHONY : sutil_sdk/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... optixBuffersOfBuffers"
	@echo "... optixCallablePrograms"
	@echo "... optixCompressedTexture"
	@echo "... optixConsole"
	@echo "... optixDenoiser"
	@echo "... optixDeviceQuery"
	@echo "... optixDynamicGeometry"
	@echo "... optixGeometryTriangles"
	@echo "... optixHello"
	@echo "... optixInstancing"
	@echo "... optixMDLDisplacement"
	@echo "... optixMDLExpressions"
	@echo "... optixMDLSphere"
	@echo "... optixMeshViewer"
	@echo "... optixMotionBlur"
	@echo "... optixParticles"
	@echo "... optixPathTracer"
	@echo "... optixPrimitiveIndexOffsets"
	@echo "... optixRaycasting"
	@echo "... optixSelector"
	@echo "... optixSphere"
	@echo "... optixSpherePP"
	@echo "... optixSSIMPredictor"
	@echo "... optixTextureSampler"
	@echo "... optixTutorial"
	@echo "... optixWhitted"
	@echo "... primeInstancing"
	@echo "... primeMasking"
	@echo "... primeMultiBuffering"
	@echo "... primeMultiGpu"
	@echo "... primeSimple"
	@echo "... primeSimplePP"
	@echo "... sutil_sdk"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

